### ISSUE TITLE
customization: Clear button, show only keybuttons

### ISSUE THREAD

**Issue by bibblebabl** [gpietro/react-numpad#100]
Hi
I really need only keypad without confirm or X button. Backspace and Clear button could replace decimal and dash buttons as well.

**Comment by gpietro** [comment]
Hi @bibblebabl,  
We don't plan to add this feature in the near future but you can try to use the KeyPad.

I suggest you to fork the project and create with your custom wrapper.

Here is an [example](https://github.com/gpietro/react-numpad/blob/ce6f9b73639ff8de8c0aa3f64a0877d90d6e1c9b/lib/components/Number.js#L66
) with the Number Component:

If you decide to do it this way let me know, if needed I can help you and we can merge your changes.

Regards,

Pietro
