### ISSUE TITLE
Prefix and Suffix

### ISSUE THREAD

**Issue by MiltonBO** [gpietro/react-numpad#116]
I was trying to use this component but I couldn't becasue we need the currency indicator, it is something that material component has. Your component is good but it is neccesary that feature I think.

**Comment by gpietro** [comment]
The library doesn't support currency at the moment.
Have you considered to wrap a custom input field with currency label set the max number of decimals?
Example: https://codesandbox.io/s/material-demo-qlifp

**Comment by MiltonBO** [comment]
Thank you about the example, it is what I was looking for.

I suggest you to document it in your Readme, because we couldn't find a good solution to this, but you understand you code.

**Comment by gpietro** [comment]
@MiltonBO you are welcome. I shoud work more on the documentation and examples.
Don't forget to support with a ⭐️  😃
