### ISSUE TITLE
Minus numpad button only enables when a number is pressed

### ISSUE THREAD

**Issue by wggley** [gpietro/react-numpad#118]
It's not a bug (Windows Calculator also works like this) but some users complained that they can't set a negative number and when investigating was this behaviour.

Could you change it so the default behaviour is the button always is enabled by default (when can put negative numbers)?

**Comment by gpietro** [comment]
Hi,
Which version of react-numpad are you using.
This bug should be fix in v.5.0.2. [example](https://codesandbox.io/s/5y2r6p8w1p).

**Comment by wggley** [comment]
Amazing, I'm still using an old release, I'll try upgrading!

Thanks
