### ISSUE TITLE
When value is provided, Numpad.Number always clear decimals.

### ISSUE THREAD

**Issue by wggley** [gpietro/react-numpad#12]
formatInputValue is called and this regular expression is running:
`value.toString().replace(/\D+/g, '');`

```
<NumPad.Number
   onChange={this.onChange}
   value="100.99"
/>
```

Also is accepting numbers like .99 and stripping minus (-)

**Comment by wggley** [comment]
Also is accepting numbers like .99

**Comment by JaiL81** [comment]
Hello,

I am facing this issue too, did you manage to solve it?

Thanks in advance.

**Comment by wggley** [comment]
Nope.

**Comment by hoodweb** [comment]
Experiencing the same. Did you by chance make a workaround or are you using another component?

**Comment by wggley** [comment]
No workaround using the same and waiting for a reply. 

In my product backlog we planned to change to it.

**Comment by bernatbombi** [comment]
Is this project still active @gpietro ? Same issue here

**Comment by gpietro** [comment]
@bernatbombi yes is active. I'm using it on different applications but until I don't face this problem, I'm not willing to invest time. If someone as some time to invest, pull requests are welcome.

**Comment by wggley** [comment]
Thanks @gpietro it worked!
