### ISSUE TITLE
Can format dot (.) to (,) for decimal places

### ISSUE THREAD

**Issue by wggley** [gpietro/react-numpad#13]
As for Brazil and other countries we use formats like:

```
Brazil = 1000,00 
US     = 1000.00
```
And also format thousands separators like:
```
Brazil = 1.000,00 / 1.000.000,00
US     = 1,000.00 / 1,000,000.00
```

**Comment by gpietro** [comment]
@wggley For the feature there is the need for another input type (Currency based on region?).

**Comment by wggley** [comment]
I'll look into it.

**Comment by gpietro** [comment]
I'm closing the issue for now.
