### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by wichaiking** [gpietro/react-numpad#143]
i can't install your package, please help.

> npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/react-numpad/-/react-numpad-5.2.1.tgz
npm ERR! 404
npm ERR! 404  'react-numpad@5.2.1' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'react-numpad-demo'
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by gpietro** [comment]
I did unpublish from npm the package by mistake.
Now it should be available with version 5.0.3
