### ISSUE TITLE
Error with update when building app

### ISSUE THREAD

**Issue by dsall** [gpietro/react-numpad#144]
Hi everybody. 
I am facing an issue with using react-numpad. It use to work fine, but in the past two days i realised that it makes my app crash when i try to run it after building it. 
It higlights the following line on the source code and message: 
react-numpad.js:22327 Uncaught TypeError: Super expression must either be null or a function, not undefined

`   if ("function" != typeof t && null !== t) throw new TypeError("Super expression must either be null or a function, not " + typeof t);
        e.prototype = Object.create(t && t.prototype, {
          constructor: {
            value: e,
            enumerable: !1,
            writable: !0,
            configurable: !0
          }`
I also noticed that they might have been an update on the package, because the import name changed from Numpad to NumPad. 
When i remove the react-numpad package, everything works fine without any issue. 
Need help solving this issue it's urgent. 

Thanks

**Comment by gpietro** [comment]
Hi,
Which version of numpad are you using in your app?

**Comment by dalenhughes** [comment]
I'm experiencing this same issue when trying to build 5.1.3
