### ISSUE TITLE
Unform TextField and react-numpad can work together?

### ISSUE THREAD

**Issue by diegobonagurio** [gpietro/react-numpad#145]
Hi!

How do I place the number keyboard inside the Form(@unform)?

`<Form ref={formRef} className={classes.form} onSubmit={handleSubmit}>
             <Grid item xs={12}>
                <NumPad.Number
                  onChange={(value) => { setNumeros(value)}}
                  variant="outlined"
                  margin="normal"
                  fullWidth
                  id="pin"
                  label="Code"
                  name="pin"
                  placeholder={"Type your code"}
                  value={numeros}
                  decimal={false}
                />
              </Grid>
            <Button
              type="submit"
              fullWidth
              variant="contained"
              color="primary"
              className={classes.submit}
            >
              {loading ? 'Loading' : 'Enter'}
            </Button>
          </Form>`

Thanks.

**Comment by gpietro** [comment]
Please follow the example custom input: https://github.com/gpietro/react-numpad#custom-input
