### ISSUE TITLE
Error when installing

### ISSUE THREAD

**Issue by lorenzosjb** [gpietro/react-numpad#150]
pm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: memberships-web@0.1.0
npm ERR! Found: @material-ui/core@4.9.8
npm ERR! node_modules/@material-ui/core
npm ERR!   @material-ui/core@"4.9.8" from the root project
npm ERR! 
**npm ERR! Could not resolve dependency:
npm ERR! peer @material-ui/core@"^4.9.14" from react-numpad@5.1.3**
npm ERR! node_modules/react-numpad
npm ERR!   react-numpad@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See /Users/macbook/.npm/eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/macbook/.npm/_logs/2020-12-07T18_00_01_712Z-debug.log
macbook@MacBook-Pro-de-macbook memberships-web %

**Comment by gpietro** [comment]
material-ui is a peer dependency and needs to be installed in you project with version 4.9.14 and above.
