### ISSUE TITLE
delete last character

### ISSUE THREAD

**Issue by bibblebabl** [gpietro/react-numpad#22]
https://github.com/gpietro/react-numpad/blob/dc2cdfe26ee99483bc3b4532ad3c04cab6b555b4/lib/elements/KeyPad.js#L95

It doesn't worked for me well in Sync mode. 
Slice doesn't work correctly. if you delete last charachter it returns empty string and doesnt modify state

I have to fork your component and put hotfix like this:

this.setState(prevState => ({
  input: prevState.input.length === 1 ? '0' : prevState.input.slice(0, -1)
}))

**Comment by gpietro** [comment]
Hi,
I did release a new version (3.0.9), can you check if it solves your problem?
The problem was the Number input validation. It did requires a non empty input to be able to confirm.
