### ISSUE TITLE
Ability to format display to a fixed number of decimal places

### ISSUE THREAD

**Issue by clarkke8** [gpietro/react-numpad#65]
It would be nice to be able to specify that the displayed value (prior to showing the number pad) be formatted with the specified number of decimal places, and on the number pad itself to only allow entering (up to) that many decimal places.

So if I specified 2 decimals places and entered "1", it would show up as "1.00", and it wouldn't allow me to enter "1.001"

**Comment by gpietro** [comment]
Solved with v4.
