### ISSUE TITLE
Warning on console when props.value is ""

### ISSUE THREAD

**Issue by clarkke8** [gpietro/react-numpad#75]
When no value is specified via "props", I am receiving the following warning on the console (in version 4.0.2):

`Warning: NumPad.getDerivedStateFromProps(): A valid state object (or null) must be returned. You have returned undefined.`

Looking at the code, I can see that you are not returning a value from "getDerivedStateFromProps" when "props.value" is not specified.

**Comment by gpietro** [comment]
Added return null when no props. fix v.4.0.3
