### ISSUE TITLE
Custom theme error

### ISSUE THREAD

**Issue by akana** [gpietro/react-numpad#77]
By following the document to customize theme,
```
const myTheme = {
  header: {
    primaryColor: '#263238',
    secondaryColor: '#f9f9f9',
    highlightColor: '#FFC107',
    backgroundColor: '#607D8B',
  },
  body: {
    primaryColor: '#263238',
    secondaryColor: '#32a5f2',
    highlightColor: '#FFC107',
    backgroundColor: '#f9f9f9',
  },
  panel: {
    backgroundColor: '#CFD8DC'
  }
};
 
<NumPad.Number theme={myTheme}>
```

I get following error

> index.js:1446 Warning: Failed prop type: Invalid prop `theme` of type `object` supplied to `KeyPad`, expected `string`

Version : 4.0.4

**Comment by gpietro** [comment]
There was a wrong propType definition. 'String' instead of 'Object'. Now it's fixed with version 4.0.5.
