### ISSUE TITLE
Add property to make the numpad visible by default

### ISSUE THREAD

**Issue by etairi** [gpietro/react-numpad#8]
I see that currently the numpad is not shown by default, and the user has to click on the input field in order for numpad to be displayed. I would like to have a property which sets the numpad visible by default when it renders. This is especially useful when one wants to render the numpad below the input field.

**Comment by gpietro** [comment]
I'll work on it. Anyway if you want to display the numpad below the input you have the position attribute: startBottonLeft, startBottonRight.

**Comment by gpietro** [comment]
Version 5.0.0-beta adds an inline prop to always display the component.
